feat: small improvements

diff --git a/config/fish/bin/dotfiles b/config/fish/bin/dotfiles
--- a/config/fish/bin/dotfiles
+++ b/config/fish/bin/dotfiles
@@ -8,58 +8,64 @@ set SUB_COMMAND_NAME $argv[2]
 set DOTFILES_DIR "$HOME/.dotfiles"
 
 function dot_help
-  echo "Usage: $BIN_NAME <command>"
-  echo
-  echo "Commands:"
-  echo "   clean            Clean up caches (brew, gem, pip)"
-  echo "   edit             Open dotfiles in IDE ($VISUAL) and Git GUI ($VISUAL_GIT)"
-  echo "   help             This help message"
-  echo "   macos            Apply macOS system defaults"
-  echo "   update           Update packages and pkg managers (brew, casks, pip3, npm, gems, macOS)"
+    echo "Usage: $BIN_NAME <command>"
+    echo
+    echo "Commands:"
+    echo "   clean            Clean up caches (brew, gem, pip)"
+    echo "   edit             Open dotfiles in IDE ($VISUAL) and Git GUI ($VISUAL_GIT)"
+    echo "   help             This help message"
+    echo "   macos            Apply macOS system defaults"
+    echo "   update           Update packages and pkg managers (brew, casks, pip3, npm, gems, macOS)"
 end
 
 function dot_clean
-  echo "\$ brew cleanup"
-  brew cleanup
-  echo "\$ gem cleanup"
-  gem cleanup
-  echo "\$ pip cache purge"
-  pip3 cache purge
+    echo "\$ brew cleanup"
+    brew cleanup --prune=all
+    echo "\$ gem cleanup"
+    gem cleanup
+    echo "\$ pip cache purge"
+    pip3 cache purge
 end
 
 function dot_edit
-  fish -c "$VISUAL $DOTFILES_DIR"
-  fish -c "$VISUAL_GIT $DOTFILES_DIR"
+    $VISUAL $DOTFILES_DIR
+    $VISUAL_GIT $DOTFILES_DIR
+end
+
+function dot_macos
+    echo "Applying macOS defaults"
+    bash "$DOTFILES_DIR/macos/defaults.sh"
+    echo "Done. Some changes may require a logout/restart to take effect."
 end
 
 function dot_update
-  echo "\$ brew upgrade"
-  brew upgrade
-  echo "\$ brew cask upgrade"
-  brew cask upgrade
-  echo "\$ pip3 install --upgrade pip"
-  pip3 install --upgrade pip
-  echo "\$ npm install -g npm"
-  npm install -g npm
-  echo "\$ gem update --system"
-  gem update --system
-  echo "\$ gem update"
-  gem update
-  echo "\$ mas upgrade"
-  mas upgrade
-  echo "\$ softwareupdate -i -a"
-  softwareupdate -i -a
+    echo '$ brew upgrade'
+    brew upgrade
+    echo '$ brew cask upgrade'
+    brew cask upgrade
+    echo '$ pip3 install --upgrade pip'
+    pip3 install --upgrade pip
+    echo '$ npm install -g npm'
+    npm install -g npm
+    echo '$ gem update --system'
+    gem update --system
+    echo '$ gem update'
+    gem update
+    echo '$ mas upgrade'
+    mas upgrade
+    echo '$ softwareupdate -i -a'
+    softwareupdate -i -a
 end
 
 switch $COMMAND_NAME
-  case "" "-h" "--help" "help"
-    dot_help
-  case "*"
-    if type -q "dot_$COMMAND_NAME"
-      eval "dot_$COMMAND_NAME"
-    else
-      echo "'$COMMAND_NAME' is not a known command or has errors."
-      dot_help
-      exit 1
-    end
+    case "" -h --help help
+        dot_help
+    case "*"
+        if type -q "dot_$COMMAND_NAME"
+            eval "dot_$COMMAND_NAME"
+        else
+            echo "'$COMMAND_NAME' is not a known command or has errors."
+            dot_help
+            exit 1
+        end
 end
